config/routes.rb
Rails.application.routes.draw do
root 'pages#home'
resources :articles
get 'signup', to: 'users#new'
resources :users, except: [:new]
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories

    validates :title, presence: true, length: {minimum:6, maximum:100}
    validates :description, presence: true, length: {minimum:10, maximum:100}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name

    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy

   # const -->> VALID_EMAIL_REGEX 
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :username, presence: true,
                         uniqueness: { case_sensitive: false },
                         length: { minimum: 3, maximum: 25 }                     
    validates :email, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [ :show, :edit, :update, :destroy ]
    before_action :require_user, except: [ :show, :index ]
    before_action :require_same_user, only: [ :edit, :update, :destroy ]

    def show
        # debugger
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 3)
    end

    def new
        @article = Article.new
    end

    def edit

    end

    def create
        #  render plain: params[:article]
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was created successfully."
            # redirect_to article_path(@article) #shortcut is -->
            redirect_to @article
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        # link_to does not work for destroy method, instead you have to use button_to 
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own article"
            redirect_to @article
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def index
        @categories = Category.paginate(page: params[:page], per_page: 3)
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 3)
    end

    def new
        @category = Category.new
    end

    def edit
        @category = Category.find(params[:id])
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category name successfully updated"
            redirect_to @category
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end

    def create
        # byebug
        user = User.find_by(email: params[:session][:email].downcase)

        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your login details"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [ :show, :edit, :update, :destroy ]
    before_action :require_user, only: [ :edit, :update ]
    before_action :require_same_user, only: [ :edit, :update, :destroy]

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 2)
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 3)
    end

    def new
        @user = User.new
    end

    def edit
      
    end

    def update
        
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated"
            redirect_to user_path
        else
            render 'edit'
        end
    end


    def create
        # byebug --> its a debugger
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, You have succesfully signed up"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated articles successfully deleted"
        redirect_to root_path
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit and delete your own account"
            redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def profile_image(user)
        image_tag("space11.jpeg", alt: user.username, class: "rounded mx-auto d-block w-25")
    end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article| %>
        
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-3 bg-white rounded">
                    <div class="card-header fst-italic">
                        <% if article.user %>
                            by <%= link_to article.user.username, user_path(article.user) %>
                        <% end %>
                        <% if article.categories.any? %>
                            <div class= "mt-2"><%= render article.categories %></div>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= article.title %></h5>
                        <p class="card-text"><%= truncate(article.description, length: 50) %></p>

                        <%= link_to "View", article_path(article), class:"btn btn-outline-success" %>
                        <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                            <%= link_to "Edit", edit_article_path(article), class:"btn btn-outline-primary" %>
                            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                        <% end %>
                    </div>
                    
                    <div class="card-footer text-body-secondary">
                        <small>Created <%= time_ago_in_words(article.created_at) %>
                        edited <%= time_ago_in_words(article.updated_at) %>
                        </small>
                    </div>
                </div>
            </div>
        </div>
        
    <% end %>


</div>

app/views/articles/_form.html.erb
<div class="container ">

  <%= render 'shared/errors', obj: @article %>

  <%= form_with(model: @article, local: true,) do |form| %>

    <div class="input-group row mb-2">
      <%= form.label :title, class: "col-2 col-form-label text-dark fw-bold shadow rounded" %>
      <div class="col-10">
        <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
      </div>
    </div>

    <div class="input-group row mb-2">
      <%= form.label :description, class: "col-2 col-form-label text-dark fw-bold shadow rounded h-25" %>
      <div class="col-10"> 
        <%= form.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
      </div>
    </div>

    <div class="input-group row">
      <%= form.label :category, class: "col-2 col-form-label text-dark fw-bold shadow rounded h-25" %>
      <div class="col-10"> 
        <%= form.collection_select :category_ids, Category.all, :id, :name, { prompt: "Make your selection from the list below(can be emply)"}, {multiple: true, size: 3, class: "form-select shadow rounded"} %>
      </div>
    </div>

    <div class="input-group row justify-content-center my-3">
      <%= form.submit class: "btn btn-primary py-2 px-4 w-25" %>
    </div>

  <% end %>

</div>

app/views/articles/edit.html.erb
<h1 class="text-center my-4"  >update the article</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to "Cancel and return to articles listing", articles_path, class: "text-decoration-none"%>
</div>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all Articles</h1>
<div class="container alpha-container">
    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>
    <%= render 'article' %>
    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>
</div>

app/views/articles/new.html.erb
<h1 class="text-center my-4" >Create a new article</h1>

 <%= render 'form' %> 

<div class="text-center" >
  <%= link_to "Cancel and return to articles listing", articles_path, class: "text-decoration-none" %>
</div>

app/views/articles/show.html.erb
<h1 class="text-center mt-4">Showing Article</h1>

<div class="container alpha-container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-3 bg-white rounded">
                <div class="card-header fst-italic">
                    by <%= link_to @article.user.username, user_path(@article.user) %>
                    <% if @article.categories.any? %>
                    <div class= "mt-2"><%= render @article.categories %></div>
                    <% end %>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= @article.title %></h5>
                    <div class="card-text"><%= simple_format(@article.description) %></div>

                    <%= link_to "Back to articles", articles_path, class:"btn btn-outline-success" %>
                    <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
                        <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-primary" %>
                        <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                    <% end %>
                </div>
                
                <div class="card-footer text-body-secondary">
                    <small>Created <%= time_ago_in_words(@article.created_at) %>
                    edited <%= time_ago_in_words(@article.updated_at) %>
                    </small>
                </div>
            </div>
        </div>
    </div>

</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill text-bg-info mx-1" %>

app/views/categories/_form.html.erb
<div class="container">


  <%= render 'shared/errors', obj: @category %>

  <%= form_with(model: @category, local: true,) do |form| %>

    <div class="input-group row mb-2">
      <%= form.label :name, "Category name", class: "col-2 col-form-label text-dark fw-bold shadow rounded" %>
      <div class="col-10">
        <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
      </div>
    </div>

    <div class="input-group row justify-content-center my-3">
      <%= form.submit class: "btn btn-primary py-2 px-4 w-25" %>
    </div>

  <% end %>

</div>

app/views/categories/edit.html.erb
<h1 class="text-center my-4"  >update the category</h1>

<%= render 'form' %> 

<div class="text-center" >
  <%= link_to "Cancel and return to category", category_path, class: "text-decoration-none" %>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Listing Categories</h1>

<div class="container">
    <div class="flickr_pagination">
        <%= will_paginate @categories, :container => false %>
    </div>
    <% @categories.each do |category| %>
        
        <div class="row justify-content-md-center">
            <div class="col-4 mt-4">
                <div class="card text-center shadow mb-3 bg-white rounded">

                    <div class="card-body">
                        <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
                        <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
                    </div>
                    
                    <div class="card-footer text-body-secondary">
                        <small>Created <%= time_ago_in_words(category.created_at) %>
                        edited <%= time_ago_in_words(category.updated_at) %>
                        </small>
                    </div>
                </div>
            </div>
        </div>
        
    <% end %>
    <div class="flickr_pagination">
        <%= will_paginate @categories, :container => false %>
    </div>
</div>

app/views/categories/new.html.erb
<h1 class="text-center my-4" >Create a new Category</h1>

<%= render 'form' %> 

<div class="text-center" >
  <%= link_to "Cancel and return to categories listing", categories_path, class: "text-decoration-none" %>
</div>

app/views/categories/show.html.erb
<h1 class="text-center my-4"  >Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
        <%= link_to "Edit category name", edit_category_path(@category),class: "btn btn-outline-primary" %>
    </div>
<% end %>

<h3 class="text-center my-4">Articles</h3>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-primary text-center text-white footer">

  <div class="container p-2">
  </div>

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2020 Copyright:
    <a class="text-white text-decoration-none fst-italic" href="https://mdbootstrap.com/">Blog news</a>
  </div>
  <!-- Copyright -->

</footer>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
        <div class="alert <%= name.to_s == "notice" ? "alert-success" : "alert-danger" %> alert-dismissible fade show" role="alert">
            <%= msg %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <%= link_to "ALPHA BLOG", root_path,class: "navbar-brand logo" %>

        <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "Bloggers", users_path, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Articles
                    </a>
                    <ul class="dropdown-menu">
                    <% if logged_in? %>
                        <li><%= link_to "create article", new_article_path, class: "dropdown-item" %></li>
                    <% end %>
                    <li><%= link_to "View articles", articles_path, class: "dropdown-item" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#"> for future</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Categories
                    </a>
                    <ul class="dropdown-menu">
                    <% if logged_in? && current_user.admin? %>
                        <li><%= link_to "create new category", new_category_path, class: "dropdown-item" %></li>
                    <% end %>
                    <li><%= link_to "View categories", categories_path, class: "dropdown-item" %></li>
                    </ul>
                </li>
                <% if logged_in? %>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %></li>
                            <li><%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %></li>
                            <li><%= link_to "Delete Profile", user_path(current_user), class: "dropdown-item text-danger",method: :delete, data: {confirm: "Are you sure?"} %></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Login", login_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Signup", signup_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlogR6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="alpha-container">
    <%= yield %>
    <div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<section class="container coverImg my-4">
    <div class="row my-4 py-5 text-center text-white">
        <div class="col-lg-12 col-md-12 my-5">
            <h1>Welcome to Home page</h1>
            <p class="my-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab neque culpa fugiat
            reiciendis, debitis officiis recusandae qui voluptatem eveniet dolorum temporibus
            quidem eius, quaerat consequuntur consectetur cupiditate iste, nihil tempora.
            </p>
            <%= link_to 'sign up!', signup_path, class: "btn btn-primary py-2 px-4" %>
        </div>
    </div>
</section>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h5 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved!</h5>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
        <strong>Check Errors!</strong> You should check in on some of those fields below.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
      
<% end %>

app/views/users/_form.html.erb
<div class="container">


  <%= render 'shared/errors', obj: @user %>

  <%= form_with(model: @user, local: true,) do |form| %>

    <div class="input-group row mb-2">
      <%= form.label :username, class: "col-2 col-form-label text-dark fw-bold shadow rounded" %>
      <div class="col-10">
        <%= form.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
      </div>
    </div>

    <div class="input-group row mb-2">
      <%= form.label :email, class: "col-2 col-form-label text-dark fw-bold shadow rounded h-25" %>
      <div class="col-10"> 
        <%= form.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email" %>
      </div>
    </div>

    <div class="input-group row mb-2">
      <%= form.label :password, class: " col-2 col-form-label text-dark fw-bold shadow rounded h-25" %>
      <div class="col-10"> 
        <%= form.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
      </div>
    </div>

    <div class="input-group row justify-content-center my-3">
      <%= form.submit(@user.new_record? ? 'sign up': 'update account', class: "btn btn-primary py-2 px-4 w-25") %>
    </div>

  <% end %>

</div>

app/views/users/edit.html.erb
<h1 class="text-center my-4"  >Edit your profile</h1>

<%= render 'form' %>

<div class="text-center">
  <%= link_to "Cancel and return to articles listing", articles_path, class: "text-decoration-none"%>
</div>

app/views/users/index.html.erb
<h1 class="text-center my-4" >Bloggers Profile</h1>

<div class="container alpha-container">
    <div class="flickr_pagination">
        <%= will_paginate @Users, :container => false %>
    </div>
    <% @users.each do |user| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-3 bg-white rounded">
                    <div class="card-header fst-italic">
                        <%= link_to user.username, user %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to profile_image(user), user %></h5>
                        <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>

                        <%= link_to "View profile", user_path(user), class:"btn btn-outline-success" %>
                        <% if logged_in? %>
                            <% if user == current_user %>
                                <%= link_to "Edit profile", edit_user_path(user), class:"btn btn-outline-primary" %>
                            <% end %>
                            <% if current_user.admin? %>
                                <%= link_to "Delete user", user_path(user), class:"btn btn-outline-danger", method: :delete,
                                data: {confirm: "Are you sure you want to delete the user and all associated articles to it ?"} %>
                            <% end %>
                        <% end %>
                    </div>
                    
                    <div class="card-footer text-body-secondary">
                        <small>Joined <%= time_ago_in_words(user.created_at) %>
                        </small>
                    </div>
                </div>
            </div>
        </div>
        
    <% end %>
    <div class="flickr_pagination">
        <%= will_paginate @Users, :container => false %>
    </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center my-4" >Sign up for Alpha Blog</h1>

 <%= render 'form' %> 

app/views/users/show.html.erb
<h1 class="text-center my-4"  ><%= @user.username %>'s profile</h1>
<%= profile_image @user %>
<% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
        <%= link_to "Edit your profile", edit_user_path(@user),class: "btn btn-outline-primary" %>
    </div>
<% end %>

<h3 class="text-center my-4">Articles</h3>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>